### ISSUE TITLE
IE Issue

### ISSUE THREAD

**Issue by Greenlark-zz** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#1]
When using internet explorer, available classes will not show.

**Comment by DrDanPrice** [comment]
Carl, did you see this issue?

**Comment by CarlSteven** [comment]
Will look into this soon.

**Comment by CarlSteven** [comment]
Fixed in https://github.com/DataAnalyticsinStudentHands/CommunityHealthWorkersApp/commit/f49edc767a9a1713a7c1e56c4103103cd32023d4
