### ISSUE TITLE
Cannot change date

### ISSUE THREAD

**Issue by vnguyen9** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#23]
http://youtu.be/oGopNPhTLbk

**Comment by CarlSteven** [comment]
Hmm... looking at backend code I don't think this is an issue with formatting the date, but rather some kind of formatting/translation issue. Will have to investigate much more.

**Comment by CarlSteven** [comment]
We are also seeing that the value turns into a NULL on the db side which must mean it is receiving an processing it to some level.
