### ISSUE TITLE
title on tabs in browser shouldn't say app

### ISSUE THREAD

**Issue by DrDanPrice** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#24]
I'd prefer "Community Health Workers Continuing Education Units" or "CHW-CEUs" (probably the shorter one). I'm not sure where it gets set.
![screen shot 2015-04-15 at 10 35 45 am](https://cloud.githubusercontent.com/assets/1826954/7162666/83274b08-e35b-11e4-95e0-d52bd0e30a44.png)

**Comment by CarlSteven** [comment]
I am not seeing this as it now shows me the title of the page in the title bar of the tab/application in both Chrome and Safari.

Chrome:
![image](https://cloud.githubusercontent.com/assets/7702743/7173247/c0262598-e3b9-11e4-818d-87309e97f09e.png)

Safari:
![image](https://cloud.githubusercontent.com/assets/7702743/7173254/d58bf976-e3b9-11e4-98ea-362208a24486.png)

I did see there was a bug with it showing "Menu" when first loading the page, so I've fixed that and updated the default title of the application in the index.html to "CHW-CEUs"

I'll leave this issue open...
