### ISSUE TITLE
[Internet Explorer on Windows 7] Log out button has scroll bar

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#29]
The log out button has a scroll bar where it does not need one.
FIX IT CARL!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hejalsoni** [comment]
![screen shot 2015-04-20 at 10 50 37 am](https://cloud.githubusercontent.com/assets/10925312/7234289/a03f1376-e74b-11e4-8df6-06b0165046be.png)

**Comment by vnguyen9** [comment]
I think it is fixed. @hejalsoni can you please verify?
