### ISSUE TITLE
[IE on Windows 7] Date picker for certification does not work

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#32]
I don't know If we need to type in a date or a small calendar is supposed to come up. Please clarify.

![capture](https://cloud.githubusercontent.com/assets/10925312/7239005/27fa40e0-e76c-11e4-9c6e-cb071667ae7f.PNG)

**Comment by CarlSteven** [comment]
Date does not show up if it determines it to be an Invalid or improperly formatted date. Will look into the root cause. Seems like we have several date issues currently active.
