### ISSUE TITLE
[Chrome on Windows 7] Classes do not get saved into Wish List

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#34]
Go to either "Available Classes" or "Training Centers", click on "Add to Wish List". Check Wish List and no class is there. The class block changes from saying "Add to Wish List" to "Remove from Wish List", but it does not get saved.

**Comment by hejalsoni** [comment]
It's on Firefox for Windows 7 too.

**Comment by CarlSteven** [comment]
Hmm... it seems to work for me. I just checked and I don't see any problems.
![image](https://cloud.githubusercontent.com/assets/7702743/7239464/adb7af26-e76f-11e4-8759-5369965d6f8f.png)

**Comment by hejalsoni** [comment]
Wait okay so this is not a problem. They just have to click the refresh button. Can we find some way to tell people to make sure to click the refresh button otherwise it does not update?

**Comment by CarlSteven** [comment]
Refreshing is the only thing that fixes the issue? For me it works without refreshing.

**Comment by hejalsoni** [comment]
That's the only thing that works for me. It does not even work if I go to the "Available Classes" page and then come back to that page
