### ISSUE TITLE
css

### ISSUE THREAD

**Issue by Greenlark-zz** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#36]
Which CSS file is the one that is mainly used for the app, is it still static_app.css?

**Comment by vnguyen9** [comment]
You have to do a
ionic setup sass

the file is <b>ionic.app.scss</b>
![screen shot 2015-04-20 at 8 47 02 pm](https://cloud.githubusercontent.com/assets/6502307/7244252/7532451a-e79e-11e4-97df-2e36af26fd2a.png)
