### ISSUE TITLE
[IE 11 windows 8] Buttons unclickable

### ISSUE THREAD

**Issue by vnguyen9** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#37]
The inspector in IE gone crazy. I'm installing windows 8 on my machine to reproduce.

**Comment by CarlSteven** [comment]
Which buttons is this?

**Comment by vnguyen9** [comment]
Any buttons in desktop view

**Comment by vnguyen9** [comment]
The doom tree is messed up in IE 11, unless the web is viewed on mobile

**Comment by CarlSteven** [comment]
@nqv1994 nav buttons seem to be working fine for me in IE 11.

**Comment by vnguyen9** [comment]
Have you tried in windows 8?

**Comment by CarlSteven** [comment]
No

**Comment by CarlSteven** [comment]
Make sure machines have the latest version of IE11 before testing, though.

**Comment by vnguyen9** [comment]
I tried the latest IE11 with Chris's laptop and on my virtual machine
