### ISSUE TITLE
[IE] Unable to Scroll

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#4]
Unable to scroll with scroll wheel, must drag to scroll.

**Comment by vnguyen9** [comment]
Turn on native scrolling?

**Comment by Greenlark-zz** [comment]
Make sure it's not the mouse itself. Some of them just stopped being able to scroll.

**Comment by vnguyen9** [comment]
I fix it in my branch. Have not merged to master.

**Comment by CarlSteven** [comment]
Now it works in IE, Chrome, and Android with great performance, but not in iOS, so something to keep in mind to fix.

We could wait for ionic 1.0 or rc2 to enable this.

**Comment by CarlSteven** [comment]
Two more notes for scrolling:
- side menu probably should have the native scrolling in IE.
- Calendar does not scroll at all, only showing 2-3 weeks in shorter windows.

**Comment by CarlSteven** [comment]
IE Calendar scrolling needs to be fixed.
