### ISSUE TITLE
Cores Change theme

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#43]
Ability to mark classes as active/inactive.

Manager should be able to see all with option.

**Comment by CarlSteven** [comment]
@nqv1994 We should add a CSS class for inactive classes and make those look different.

**Comment by CarlSteven** [comment]
Will be handled in #45. And then we can add the CSS

**Comment by CarlSteven** [comment]
@nqv1994 I've done all this functionality from #38, #45, #43 in the feature/addFields branch. let's think about how the CSS/visual aspect of these fields and and checkboxes will look like.

Examples of what's there now:
![image](https://cloud.githubusercontent.com/assets/7702743/7501868/2cb65dc4-f3fd-11e4-8552-468b492058cc.png)

**Comment by vnguyen9** [comment]
Awesome!

I’ll work on it Friday.

**Comment by CarlSteven** [comment]
I've added the active/inactive.
![image](https://cloud.githubusercontent.com/assets/7702743/7571136/1c257684-f7db-11e4-9122-d56944eb5793.png)

**Comment by CarlSteven** [comment]
https://docs.angularjs.org/api/ng/directive/ngClass

**Comment by vnguyen9** [comment]
I think adding icon/ badge should look better. What do you think?
