### ISSUE TITLE
[Chrome on Mavericks] Button disappeared

### ISSUE THREAD

**Issue by hejalsoni** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#53]
(Signed in as manager)
1. Minimize screen
2. Open screen back up
3. Click on settings
The top button that opens up the side bar disappeared.

**Comment by CarlSteven** [comment]
Please provide a screenshot of the button that has disappeared. I'm not sure which one you mean.

**Comment by hejalsoni** [comment]
![image](https://cloud.githubusercontent.com/assets/10925312/7349682/833c7a8c-ecc0-11e4-9071-73ad81f13ed1.png)

**Comment by hejalsoni** [comment]
^Elizabeth said that it was that button on the top left side. The 3 line one.

**Comment by CarlSteven** [comment]
I can’t reproduce this. Was the menu button supposed to be visible?

Please note, when the browser is beyond a certain width and the menu is visible by default, the menu button should not be visible. 

Carl

**Comment by hejalsoni** [comment]
According to Elizabeth, it happened once and never again. I tried it and I could not reproduce it, but I just thought to put in GitHub just in case.

**Comment by CarlSteven** [comment]
Hmm... I'm gonna close this, please reopen if reproducible.
