### ISSUE TITLE
Rearrange Buttons on Headerbar

### ISSUE THREAD

**Issue by vnguyen9** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#55]
![screen shot 2015-05-11 at 1 07 17 pm](https://cloud.githubusercontent.com/assets/6502307/7571869/06fcfb60-f7e0-11e4-89c7-836aed376eb1.png)

**Comment by CarlSteven** [comment]
Is this closed by https://github.com/DataAnalyticsinStudentHands/CommunityHealthWorkersApp/commit/9cc943e6c3f6b130de0b34dc06150a41281a9544?
