### ISSUE TITLE
Can't Add Classes

### ISSUE THREAD

**Issue by Greenlark-zz** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#6]
When you clicking submit in order to add a task, nothing happens. It doesn't even give an error, it simply wont do anything. At first I thought that maybe my map code was interfering so I took it out but even plainly without locations, it still won't submit.

**Comment by CarlSteven** [comment]
I can add and edit classes in the version on Housuggest. Make sure you've pulled from master/using the latest version, please.

**Comment by Greenlark-zz** [comment]
Ok, it seemed that my version just didn't want to update for some reason. Everything is now working properly, thanks.
