### ISSUE TITLE
Class Options

### ISSUE THREAD

**Issue by CarlSteven** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#9]
a) Map is shown instead of Info
~~b) More Info is shown instead of Add to Wish List~~
~~c) No option to Edit or Delete~~ #10

**Comment by CarlSteven** [comment]
a) When I click on "Info" it takes me to the right page, but that page needs a map of the class.
b) Looks like it's been handled
c) These are definitely there, but sometimes hidden off-screen #10

**Comment by Greenlark-zz** [comment]
Maps and address field are now up and working.

**Comment by CarlSteven** [comment]
When I click on a class, this is what I see:
![image](https://cloud.githubusercontent.com/assets/7702743/7088064/b750a2ac-df56-11e4-9d8f-d14e29089735.png)

Location and map are not showing up. I'm working off of the latest commit in master.

**Comment by Greenlark-zz** [comment]
Map are not available for most classes because they didn't have an address field when they were made. If you made a new class and entered an address it would appear.

**Comment by CarlSteven** [comment]
Just updated the backend to support editing of classes to persist address field. Also, we need a fallback if the map is not available, right now it prevents loading the state.

**Comment by CarlSteven** [comment]
Closing this because this seems to be done.
